qUES 4

APPROACH 1

SELECT D1.DEPT_NAME,E1.EMP_ID,E1.SALARY FROM DEPARTMENT AS D1
LEFT JOIN EMPLOYEE AS E1
ON D1.DEPT_ID=E1.DEPT_ID
AND E1.SALARY=(

SELECT MAX(E3.SALARY) FROM EMPLOYEE AS E3
WHERE E3.DEPT_ID=E1.DEPT_ID
AND E3.SALARY<
(
SELECT MAX(E2.SALARY) FROM EMPLOYEE AS E2
WHERE E2.DEPT_ID=E1.DEPT_ID

)
)

-APPROACH 2 



SELECT D1.DEPT_NAME,E1.EMP_ID,E1.SALARY 
FROM DEPARTMENT AS D1
LEFT JOIN EMPLOYEE AS E1
ON D1.DEPT_ID=E1.DEPT_ID
WHERE
(
SELECT COUNT(DISTINCT E2.SALARY) FROM EMPLOYEE AS E2
WHERE E2.DEPT_ID=E1.DEPT_ID
AND E2.SALARY>E1.SALARY

QUES 5

-- Create Table
CREATE TABLE StudentMarks (
    Sname VARCHAR(10),
    Sid CHAR(1),
    Marks INT
);

-- Insert Data
INSERT INTO StudentMarks VALUES
('A', 'X', 75),
('A', 'Y', 75),
('A', 'Z', 80),
('B', 'X', 90),
('B', 'Y', 91),
('B', 'Z', 75);  

', 'Z', 75);


SELECT S1.SNAME ,SUM(DISTINCT S1.MARKS) AS MARKS 
FROM StudentMarks AS S1
WHERE (
SELECT COUNT(DISTINCT S2.MARKS)
FROM StudentMarks AS S2
WHERE S2.MARKS>S1.MARKS AND S2.SNAME=S1.SNAME
)<=1
GROUP BY S1.SNAME



----------------------------------
CREATE TABLE test_data (
    col1 INT,
    col2 VARCHAR(50)
);

INSERT INTO test_data (col1, col2) VALUES
(1, 'A,B,C'),
(2, 'A,

)


SELECT col1, LENGTH(COL2)-LENGTH(REPLACE(COL2,',',''))+1 AS COL2
FROM TEST_DATA